var mongoose = require('mongoose');
// Setup Mongo DB to store twitter stream
module.exports = mongoose.model('twitterStream', {
  created_at : {type : String, default: ''},
  id_str : {type : String, default: ''},
  text : {type : String, default: ''},
  source : {type : String, default: ''},
  user_id_str : {type : String, default: ''},
  user_name : {type : String, default: ''},
  user_screen_name : {type : String, default: ''},
  user_followers_count : {type : String, default: 0},
  user_friends_count : {type : String, default: 0},
  user_listed_count : {type : String, default: 0},
  user_favourites_count : {type : String, default: 0},
  user_statuses_count : {type : String, default: 0},
  user_created_at : {type : String, default: ''},
  geo_type : {type : String, default: ''},
  geo_coordinates_lat : {type : String, default: 0.0},
  geo_coordinates_lng : {type : String, default: 0.0},
  coordinates_type : {type : String, default: ''},
  coordinates_lat : {type : String, default: 0.0},
  coordinates_lng : {type : String, default: 0.0},
  place_id : {type : String, default: ''},
  place_url : {type : String, default: ''},
  place_type : {type : String, default: ''},
  place_name : {type : String, default: ''},
  place_full_name : {type : String, default: ''},
  place_country_cd : {type : String, default: ''},
  place_country : {type : String, default: ''},
  lang : {type : String, default: ''},
  timestamp_ms : {type : String, default: ''},
});
